<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TestRid Condition="'$(TestRid)' == ''">linux-x64</TestRid>
    <SupprocomPackageId Condition="'$(SupprocomPackageId)' == ''">Supprocom.FFmpeg.Binaries.$(TestRid)</SupprocomPackageId>
    <SupprocomPackageVersion Condition="'$(SupprocomPackageVersion)' == ''">9.0.2</SupprocomPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(SupprocomPackageId)" Version="$(SupprocomPackageVersion)" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"
                      Version="1.0.3"
                      PrivateAssets="all"
                      Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
  </ItemGroup>
</Project>
